export interface Champion {
  id: string,
  key: string,
  name: string,
  title: string,
  lore: string,
  info: {
    attack: number,
    defense: number,
    magic: number,
    difficulty: number,
  },
  image: {
    full: string,
    sprite: string,
    group: string,
  },
  tags: Array<string>,
  partype: string,
  stats: {
    hp: number,
    hpperlevel: number,
    mp: number,
    mpperlevel: number,
    movespeed: number,
    armor: number,
    armorperlevel: number,
    spellblock: number,
    spellblockperlevel: number,
    attackrange: number,
    hpregen: number,
    hpregenperlevel: number,
    mpregen: number,
    mpregenprelevel: number,
    crit: number,
    critperlevel: number,
    attackdamage: number,
    attackdamageperlevel: number,
    attackspeedperlevel: number,
    attackspeed: number,
  },
}
